version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis:6379
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"